### ISSUE TITLE
Table.write

### ISSUE THREAD

**Issue by sylwiabr** [luna/Dataframes#105]
We need the write method to save Table to the file - figure out the format from extension, if format like `txt` is given use csv.

**Comment by sylwiabr** [comment]
When I am trying to write 
[foo.txt](https://github.com/luna/Dataframes/files/2686810/foo.txt) as an xlsx file I don't have proper dates 
[foo.xlsx](https://github.com/luna/Dataframes/files/2686811/foo.xlsx) @mwu-tow

**Comment by mwu-tow** [comment]
The dates are properly placed in the file. You might need to resize the column to see it though to fully fit it.
