### ISSUE TITLE
Crash on Table.read when using Dataframes built from sources from Luna Studio

### ISSUE THREAD

**Issue by mwu-tow** [luna/dataframes#110]
The following crashes Luna Empire when I use Dataframes built from sources:

```
import Std.Base
import Std.Foreign.C.Value

import Dataframes.Internal.Utils
import Dataframes.Array
import Dataframes.Table
import Dataframes.Types
import Dataframes.Internal.Test.Test


«0»def main:
    «1»Table . read "./data/tricky.csv"
    None
```

It works when using packaged Dataframes. It works also with shell luna.
Confirmed on Ubuntu 18.04.

**Comment by mwu-tow** [comment]
Confirmed on Fedora 28.
No issue on Windows.(

**Comment by mikusp** [comment]
It would be helpful if you provided stack trace of crash

**Comment by mwu-tow** [comment]
The crash is coming from Dataframes module initialization:
```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
```

**Comment by mwu-tow** [comment]
O believe it should work once PYTHONHOME and PYTHONPATH are appropriately set. 
But what really puzzles me is why it works in shell luna (and tests executable) but fails only in luna-empire.

**Comment by mwu-tow** [comment]
Actually I pinned the issue. `PYTHONHOME` and `PYTHONPATH` are for some reason set in luna-empire process to some stupid values. That cause Python interpreter to look for its standard library in wrong place and refuse to setup what causes Dataframes in turn to fail to load and the issue observed.

The question remains why the luna-empire has these variables set.

**Comment by mwu-tow** [comment]
And I think we have the culprit: https://github.com/AppImage/AppImageKit/blob/appimagetool/master/src/AppRun.c#L169

**Comment by sylwiabr** [comment]
@mwu-tow we can deal with it setting proper variable in runner/supervisor
