### ISSUE TITLE
Build failure with MSVC >= 15.9

### ISSUE THREAD

**Issue by mwu-tow** [luna/dataframes#113]
Dataframes currently fail to build on Visual Studio with latest update installed (15.9.3). This is a regression in the compiler. The 15.8 release works fine. Issue has been reduced and reported to MS: https://developercommunity.visualstudio.com/content/problem/395993/159-regression-error-on-valid-c-code-constexpr-if.html

They fixed the issue but it is unclear when the fix will be released and whether it will be backported to VS 2017. AppVeyor still works on 15.8, so CI is unaffected. For developer builds, it is recommended to use 15.8 toolset as well (it can be installed side-by-side with 15.9).

At the moment no action is required, if AppVeyor updates the image before MS releases the fix, we should add some workaround either to avoid issue or force the supported toolset version.

**Comment by mwu-tow** [comment]
For now issue has been worked around by forcing previous VM image in appveyor config: https://github.com/luna/Dataframes/commit/be451e2dafa638279193d55a365ea2c5e0ba8456

In the longer term it can be solved by AppVeyor by adding 15.8 toolset component in their image: https://github.com/appveyor/ci/issues/2783

**Comment by sylwiabr** [comment]
We don't care.
