### ISSUE TITLE
Handle non-native line endings in csv parser

### ISSUE THREAD

**Issue by mwu-tow** [luna/Dataframes#18]
### General Summary
Reading CSV with Windows-style line endings (CRLF) does not work properly on Mac/Linux, as CR-LF is not properly handled on non-Windows platforms.

**Comment by mwu-tow** [comment]
Using file streams in text mode causes our "grab whole file" reading approach unreliable on Windows as well.

**Comment by mwu-tow** [comment]
It should be fixed now but I don't have an easy way to test it. 
@sylwiabr You had previously encountered this issue on Mac. Could you please check if the issue is solved now?

**Comment by sylwiabr** [comment]
It is!

**Comment by mwu-tow** [comment]
Thanks!

**Comment by sylwiabr** [comment]
We will close it as soon as we release package with Dataframes. For now it is `Release blocked`

**Comment by mwu-tow** [comment]
It shouldn't be release blocked if the last public release didn't contain this bug.

**Comment by sylwiabr** [comment]
The public release didn't contain Dataframes at all.

**Comment by mwu-tow** [comment]
That's the point. The bug was never released, so there is no sense in keeping it open until the release.

**Comment by sylwiabr** [comment]
I think this should be discussed with @lgawlik
