### ISSUE TITLE
Appveyor Builds for C++

### ISSUE THREAD

**Issue by iamrecursion** [luna/Dataframes#21]
### Summary
Currently it is proving difficult to know if the C++ components of dataframes are able to build successfully on all of our supported platforms. To ensure that they do, Appveyor CI (for windows support) should be set up to build these components. 

### Value
Having this set up will allow a faster development cadence as we can rely on the CI infrastructure to detect issues ahead of time, rather than finding the issues later on. 

### Specification

- Set up the dataframes repo with Appveyor CI.
- Have appveyor CI build the C++ components of this repo on Linux, MacOS and Windows. 

### Acceptance Criteria & Test Cases

- Appveyor is able to build this code, and reports build success or failure for every commit.

**Comment by mwu-tow** [comment]
I have added CircleCI integration building & testing C++ parts on GCC-7 and GCC-8. https://circleci.com/gh/luna/Dataframes
AppVeyor is next. Then, likely, a Mac.
