### ISSUE TITLE
Revise the current API

### ISSUE THREAD

**Issue by sylwiabr** [luna/dataframes#26]
Some points that have been raised:
 * ```max of a column is not a number, but a column (I understand why that is so, but it is not nice to work with)```
* ``` The map over a column works in a way that gets me totally lost. I need to specify the type of the column: but I don't know it in the first place. That's a big win for pandas, where I can map like I know it.```

**Comment by sylwiabr** [comment]
maybe `describe` method should be for whole Dataframe and `describeColumn` sholud take `columnName` and do what current `describe` does? @piotrMocz @kustosz ?

**Comment by mwu-tow** [comment]
Case: user has a table, wants to fill nulls in each column with a mean value for that column

**Comment by piotrMocz** [comment]
The thing I have very strong feelings about:
the `Table` class should expose the `read<Format>` method. Please keep in mind that we're not targetting expert programmers or even hobbyist programmers, but "data profesionals".

`Table.readCSV` is a method that gives you a table from a CSV file. `Table.readXLS` is a method that gives you a table from an Excel file. And so on. Accidentally, this is exactly how `pandas` does it. Advantages:
* single import for `Table` read and for `Table` processing
* "ideological" compatibility with `pandas`
* hides the implementation details and makes the API dead simple

Currently you write `CSVParser.readFile`. Let's look at the drawbacks:
* when processing data, you need another entity: some parser. I wouldn't want to have to know about some parsers when all I want to do is to read a dataframe from file
* one more concept to keep track of
* one more import

All in all, I suggest we at least add the `Table.readCSV = CSVParser.readFile` alias.

Like, really, please 😅

**Comment by sylwiabr** [comment]
All non-user facing functions should have `_` prefix

**Comment by sylwiabr** [comment]
@piotrMocz what do you rthink about https://github.com/luna/Dataframes/issues/57 in context of reading/writing files?

**Comment by wdanilo** [comment]
Moreover, the `toInt` method should be named `toEnum`

**Comment by sylwiabr** [comment]
`Table.fromFile` should have better name (more descriptive)

**Comment by sylwiabr** [comment]
`removeColumn` -> `removeByIndex`

**Comment by sylwiabr** [comment]
`keep` as opposite to `remove`

**Comment by sylwiabr** [comment]
`corr` -> `correlations`
`corrWith` -> `correlationsWith`

**Comment by sylwiabr** [comment]
change generated names from `CORR_WITH_foo` to `corr_with_foo`

**Comment by sylwiabr** [comment]
sort -> sortMultiple
sort Descending by default
sort config (?)

**Comment by piotrMocz** [comment]
> @piotrMocz what do you rthink about #57 in context of reading/writing files?

I left a comment there ;)

**Comment by sylwiabr** [comment]
`plotVerticalLayout [Plot]` - to remove when lazy vis appears
