### ISSUE TITLE
Histogram does not display properly on linux while working perfectly on MacOS

### ISSUE THREAD

**Issue by sylwiabr** [luna/dataframes#28]
download and build `Dataframes` project
checkout on commit `3d35ac29117a4551fd2281db240ba88a60f2984e`
on linux we have:
![unknown](https://user-images.githubusercontent.com/12892578/45355845-d31cdd80-b5c1-11e8-8281-fba32a9a593e.png)
while on MacOS histogram is generated without any problems.
The dataset used for this issue is gaggle Two Sigma dataset

**Comment by mwu-tow** [comment]
Clickable link for future convenience: https://github.com/luna/Dataframes/commit/3d35ac29117a4551fd2281db240ba88a60f2984e#diff-2de10126e70260e5b1486670cffa7b4c

**Comment by mwu-tow** [comment]
Fix confirmed.
