### ISSUE TITLE
Rolling window operations for DataFrames

### ISSUE THREAD

**Issue by piotrMocz** [luna/Dataframes#35]
Pandas provides [a great API for rolling window computations](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.rolling.html).

Ideally, we would have two kinds of windows:
1. constant time interval window for time series
2. constant number of samples window for the general case.

**Comment by sylwiabr** [comment]
Where we are with the part: `constant number of samples window for the general case.` @mwu-tow ?

**Comment by mwu-tow** [comment]
Not started and outside our immediate plans.

**Comment by sylwiabr** [comment]
So this should go back to backlog? @lgawlik

**Comment by sylwiabr** [comment]
Issue for second part is here: https://github.com/luna/Dataframes/issues/53
