### ISSUE TITLE
Dataframe API docstrings

### ISSUE THREAD

**Issue by piotrMocz** [luna/Dataframes#38]
For every public function there needs to be a docstring outlining its general purposeand parameters. For key functions we need a more detailed description of how the functions work and some examples.

As a side-task, we need to come up with a template for a good docstring (the long one). Here is some inspiration: https://www.python.org/dev/peps/pep-0257/ and the pandas API is well documented, with lots of examples.

NOTE: this is a rather cumbersome task, but very important.

**Comment by sylwiabr** [comment]
I think since we have RFC part for this the discussion should be there. Part of this was done by https://github.com/luna/Dataframes/pull/52. The rest will go with further improvements of the API
