### ISSUE TITLE
Writing file with relative path is not working correctly

### ISSUE THREAD

**Issue by sylwiabr** [luna/Dataframes#55]
Repro steps:
```
import Dataframes.Column 
import Dataframes.Types
import Dataframes.Table 
l1 = [1,2,3,4,5]
l2 = [11,12,13,14,15]
col1 = Column.fromList "col1" Int64Type l1
col2 = Column.fromList "col2" Int64Type l2
table = Table.fromColumns [col1 , col2]
CSVGenerator . writeFile "./data/foo.csv" table
```
is not saving to `./data` folder while giving full path is saving everything correctly

Required behavior:
We should not expand the relative paths magically. We should use the Current Working Directory env variable, which should be set to project root. We need to check if it is set so, or the problem is caused by something else.

**Comment by mwu-tow** [comment]
Works for me. Please give the full repro steps (actual code and how do you run it).

If you're using Luna Studio remember that Current Working Directory is coming from luna-empire and it might not be what user is expecting.

**Comment by mwu-tow** [comment]
Please also check if standard library's `writeFile` work as expected. 
Note: for luna-empire the CWD on my machine is `C:\Program Files\LunaStudio\1.5\config\windows\`

**Comment by mikusp** [comment]
Current directory is set to current package directory during evaluation

**Comment by mwu-tow** [comment]
@mikusp  Your are right. I just pasted the code as main in Dataframes project and opened it in Luna Studio. The file appeared correctly in the project's subtree.

**Comment by sylwiabr** [comment]
Ok, I can see now. It is just Atom having delay on refreshing tree view.
