### ISSUE TITLE
reading/writing files

### ISSUE THREAD

**Issue by sylwiabr** [luna/dataframes#57]
for reading/writing files we should have:
1. `CSV.read` and `CSV.write` functions
2. general method which will check file extension: `Table.read` and `Table.write`
If the extension is `txt` or there is none it should try to read it with all available methods.

**Comment by piotrMocz** [comment]
@sylwiabr  `Table.read` is cool. `CSV.read` is fine, much better than `CSVParser.readFile` 👍 

However, I don't understand why we're so afraid of the `Table.read_csv` method, which will support intuition people have got from Pandas/R ;) (Aside from the circular dependencies problem which @mwu-tow mentioned, but that applies equally to `Table.read`.
