### ISSUE TITLE
`Table.drop` with negative argument returns strange values

### ISSUE THREAD

**Issue by sylwiabr** [luna/Dataframes#63]
code to reproduce:
```
import Dataframes.Table
import Dataframes.Types
import Dataframes.Column
def main:
    l2 = [11,12,13,14,15]
    l1 = [1,2,3,4,5]
    col1 = Column . fromList "col2" Int64Type l1
    col2 = Column . fromList "col2" Int64Type l2
    table = Table . fromColumns [col1 , col2 ]
    take1 = table . drop -7
    None
```
output:
![obraz](https://user-images.githubusercontent.com/12892578/46482725-72667680-c7f6-11e8-93fa-d4618b616dfa.png)
I would suspect that if an argument for drop is negative the `self` table will be returned

**Comment by sylwiabr** [comment]
@mwu-tow  if so then `Table.take` should behave the same way and report errors.

**Comment by sylwiabr** [comment]
@mwu-tow should it go to Acceptance column?

**Comment by mwu-tow** [comment]
Yup.
