### ISSUE TITLE
Table.fromFile does not recognize XLSX files

### ISSUE THREAD

**Issue by mwu-tow** [luna/Dataframes#66]
I should be able to read Dataframe when using `Table.fromFile "path/to/file.xlsx`

**Comment by sylwiabr** [comment]
on MacOS `Table.readFile` on  xlsx file returns strange results still
<img width="454" alt="zrzut ekranu 2018-10-24 o 08 45 34" src="https://user-images.githubusercontent.com/12892578/47411509-45f4a900-d769-11e8-814d-49313982f327.png">

**Comment by mwu-tow** [comment]
What's the file? The sample one from repo? Path is not visible on the screenshot.
I just run 
```
def main:
    t = Table.fromFile "./data/sample_xlsx.xlsx"
    print t
```
and got 
```
Running in interpreted mode.
[[4, 7, 10], [, 8, 11], [6, 9, 12]]
```
so there must be something more to this issue.

Please try:
1) If running the main above works in Luna Studio on Mac
2) If not — does it work in shell Luna?

Also, just to be absolutely sure — you have latest master and have built the project after pull?

**Comment by sylwiabr** [comment]
Ok there was sth wrong with my xlnt library build

**Comment by mikusp** [comment]
Works as Table.read
