### ISSUE TITLE
Building relocatable Linux packages in CI

### ISSUE THREAD

**Issue by mwu-tow** [luna/Dataframes#94]
Similarly to what was done with AppVeyor #67 we need an equivalent for Linux builds. The packaging script needs to be appropriately developed. We expect our Linux CI (CircleCI) to output relocatable Dataframes package as an build artifact.

**Comment by sylwiabr** [comment]
should this go to acceptance @mwu-tow ?

**Comment by mwu-tow** [comment]
Yes. Now we need Linux luna-studio package with this Dataframes and give it some testing.

**Comment by sylwiabr** [comment]
@mikusp can you try it while building next packages?

**Comment by mwu-tow** [comment]
**mikusp** prepared the first luna-studio package for Linux that contains the Dataframe package: 
https://github.com/luna/luna-studio/releases/download/1.5.100.113/luna-studio-linux-1.5.100.113-dataframes.AppImage

Please give it some testing. For example, try pasting the following:
```
import Dataframes.Table
import Dataframes.Types
import Dataframes.Column
import Std.Base

def main:
    fromList1 = Column . fromList "a" Int64Type [1,2,3,4,5]
    fromColumns1 = Table . fromColumns [fromList1]
    plot1 = fromColumns1 . plot "a" "a"
    None
``` 
and see if chart appears.

**Comment by mwu-tow** [comment]
wdanilo reported the following:
![image](https://user-images.githubusercontent.com/1548407/48624277-4a992f80-e9ac-11e8-8493-5ffa9b093ffd.png)

It looks like in issue coming from our dynamic linker, @mikusp  will look into this.

**Comment by mwu-tow** [comment]
On wdanilo's system ldconfig command is not visible:
```
wdanilo@phoenix ~> ldconfig -p
fish: Unknown command 'ldconfig'
```
